### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by xyxxyx** [shicai/Weighted_Softmax_Loss#2]
我按照使用说明配置后，重新编译caffe，会报错如下，

src/caffe/layers/weighted_softmax_loss_layer.cpp:144:1:   required from here
src/caffe/layers/weighted_softmax_loss_layer.cpp:116:29: error: 'class caffe::Blob<double>' has no member named 'shape'
           for (int c = 0; c < bottom[0]->shape(softmax_axis_); ++c) {
                             ^

我回溯了一下发现更靠前的错误是
src/caffe/layers/weighted_softmax_loss_layer.cpp:145:45: error: macro "REGISTER_LAYER_CLASS" requires 2 arguments, but only 1 given
 REGISTER_LAYER_CLASS(WeightedSoftmaxWithLoss);
                                             ^
不知道该如何解决？

**Comment by shicai** [comment]
REGISTER_LAYER_CLASS 只需要一个参数啊，不需要2个的。
你要不检查下是不是caffe的问题？

**Comment by xyxxyx** [comment]
@shicai  我看了，或许是因为我用的caffe版本比较旧。不知道你是基于哪个版本的caffe写的并运行成功的？

**Comment by shicai** [comment]
代码是去年八九月写的，那时候可以运行，那之后的应该都可以吧，你要不对比下softmax_loss的代码，稍微看看哪里不同，简单改下就可以用的。

**Comment by xyxxyx** [comment]
好的，非常感谢~是这样的，我现在在用deeplab-v1的代码，这个依赖于自己版本的caffe（比较旧）。我现在想在这里面用一下weight soft max来实现一个想法。

在 2016-06-28 20:28:59，shicai notifications@github.com 写道：

代码是去年八九月写的，那时候可以运行，那之后的应该都可以吧，你要不对比下softmax_loss的代码，稍微看看哪里不同，简单改下就可以用的。

**Comment by xyxxyx** [comment]
@shicai 
我更新了caffe的版本，可以成功运行后试着加入weighted_softmaxloss_layer，结果报错

src/caffe/layers/weighted_softmax_loss_layer.cpp:13:34: error: expected initializer before '<' token
 void WeightedSoftmaxWithLossLayer<Dtype>::LayerSetUp(
                                  ^
src/caffe/layers/weighted_softmax_loss_layer.cpp:38:34: error: expected initializer before '<' token
 void WeightedSoftmaxWithLossLayer<Dtype>::Reshape(
                                  ^
src/caffe/layers/weighted_softmax_loss_layer.cpp:60:34: error: expected initializer before '<' token
 void WeightedSoftmaxWithLossLayer<Dtype>::Forward_cpu(
                                  ^
src/caffe/layers/weighted_softmax_loss_layer.cpp:97:34: error: expected initializer before '<' token
 void WeightedSoftmaxWithLossLayer<Dtype>::Backward_cpu(const vector<Blob<Dtype>_>& top,
                                  ^
In file included from ./include/caffe/blob.hpp:8:0,
                 from ./include/caffe/layer.hpp:8,
                 from src/caffe/layers/weighted_softmax_loss_layer.cpp:5:
src/caffe/layers/weighted_softmax_loss_layer.cpp:144:19: error: 'WeightedSoftmaxWithLossLayer' is not a class template
 INSTANTIATE_CLASS(WeightedSoftmaxWithLossLayer);
                   ^
./include/caffe/common.hpp:43:18: note: in definition of macro 'INSTANTIATE_CLASS'
   template class classname<float>; \
                  ^
src/caffe/layers/weighted_softmax_loss_layer.cpp:144:19: error: explicit instantiation of non-template type 'caffe::WeightedSoftmaxWithLossLayer'
 INSTANTIATE_CLASS(WeightedSoftmaxWithLossLayer);
                   ^
./include/caffe/common.hpp:43:18: note: in definition of macro 'INSTANTIATE_CLASS'
   template class classname<float>; \
                  ^
src/caffe/layers/weighted_softmax_loss_layer.cpp:144:19: error: 'WeightedSoftmaxWithLossLayer' is not a class template
 INSTANTIATE_CLASS(WeightedSoftmaxWithLossLayer);
                   ^
./include/caffe/common.hpp:44:18: note: in definition of macro 'INSTANTIATE_CLASS'
   template class classname<double>
                  ^
src/caffe/layers/weighted_softmax_loss_layer.cpp:144:19: error: explicit instantiation of non-template type 'caffe::WeightedSoftmaxWithLossLayer'
 INSTANTIATE_CLASS(WeightedSoftmaxWithLossLayer);
                   ^
./include/caffe/common.hpp:44:18: note: in definition of macro 'INSTANTIATE_CLASS'
   template class classname<double>
                  ^
In file included from ./include/caffe/layer.hpp:10:0,
                 from src/caffe/layers/weighted_softmax_loss_layer.cpp:5:
src/caffe/layers/weighted_softmax_loss_layer.cpp: In function 'boost::shared_ptrcaffe::Layer<Dtype > caffe::Creator_WeightedSoftmaxWithLossLayer(const caffe::LayerParameter&)':
src/caffe/layers/weighted_softmax_loss_layer.cpp:145:22: error: 'caffe::WeightedSoftmaxWithLossLayer' is not a template
 REGISTER_LAYER_CLASS(WeightedSoftmaxWithLoss);
                      ^
./include/caffe/layer_factory.hpp:135:42: note: in definition of macro 'REGISTER_LAYER_CLASS'
     return shared_ptr<Layer<Dtype> >(new type##Layer<Dtype>(param));           \
                                          ^
./include/caffe/layer_factory.hpp:135:66: error: invalid use of incomplete type 'class caffe::WeightedSoftmaxWithLossLayer'
     return shared_ptr<Layer<Dtype> >(new type##Layer<Dtype>(param));           \
                                                                  ^
src/caffe/layers/weighted_softmax_loss_layer.cpp:145:1: note: in expansion of macro 'REGISTER_LAYER_CLASS'
 REGISTER_LAYER_CLASS(WeightedSoftmaxWithLoss);
 ^
In file included from ./include/caffe/blob.hpp:8:0,
                 from ./include/caffe/layer.hpp:8,
                 from src/caffe/layers/weighted_softmax_loss_layer.cpp:5:
src/caffe/layers/weighted_softmax_loss_layer.cpp:144:19: error: forward declaration of 'class caffe::WeightedSoftmaxWithLossLayer'
 INSTANTIATE_CLASS(WeightedSoftmaxWithLossLayer);
                   ^
./include/caffe/common.hpp:43:18: note: in definition of macro 'INSTANTIATE_CLASS'
   template class classname<float>; \
                  ^
In file included from ./include/caffe/layer.hpp:10:0,
                 from src/caffe/layers/weighted_softmax_loss_layer.cpp:5:
src/caffe/layers/weighted_softmax_loss_layer.cpp: In function 'boost::shared_ptrcaffe::Layer<Dtype > caffe::Creator_WeightedSoftmaxWithLossLayer(const caffe::LayerParameter&) [with Dtype = double]':
./include/caffe/layer_factory.hpp:136:3: warning: control reaches end of non-void function [-Wreturn-type]
   }                                                                            \
   ^
src/caffe/layers/weighted_softmax_loss_layer.cpp:145:1: note: in expansion of macro 'REGISTER_LAYER_CLASS'
 REGISTER_LAYER_CLASS(WeightedSoftmaxWithLoss);
 ^
src/caffe/layers/weighted_softmax_loss_layer.cpp: In function 'boost::shared_ptrcaffe::Layer<Dtype > caffe::Creator_WeightedSoftmaxWithLossLayer(const caffe::LayerParameter&) [with Dtype = float]':
./include/caffe/layer_factory.hpp:136:3: warning: control reaches end of non-void function [-Wreturn-type]
   }                                                                            \
   ^
src/caffe/layers/weighted_softmax_loss_layer.cpp:145:1: note: in expansion of macro 'REGISTER_LAYER_CLASS'
 REGISTER_LAYER_CLASS(WeightedSoftmaxWithLoss);
 ^
make: *_\* [.build_release/src/caffe/layers/weighted_softmax_loss_layer.o] Error 1

不知道您有什么看法？

**Comment by xyxxyx** [comment]
已解决。

**Comment by MuseCP** [comment]
你好，我在修改deeplabV2的源码的时候也碰上了这个问题，不知道最后您是怎样解决的？
