### ISSUE TITLE
Multi classification problem 

### ISSUE THREAD

**Issue by zhanglaplace** [shicai/Weighted_Softmax_Loss#7]
您好，谢谢你的源码分享，
请问pos_cid_ 和pos_mult_ 的数据类型应该只是针对二分类吧，
如果针对多分类，可以修改为vector吧。

**Comment by shicai** [comment]
是的，可以使用一个class_weight的向量来做

**Comment by zhanglaplace** [comment]
好的，谢谢，我尝试用sliceLayer的slicePoint模式，设置repeate float weight_cls

**Comment by sophiazy** [comment]
@shicai @zhanglaplace 您好，我的情况多分类问题是这样的，我总共有21个类别，其中20个类别的样本数量是均衡的，只有一个类别数量比其他类别多几倍，那您分享的这个Weighted_Softmax_Loss适用我这种情况吗？希望得到您的回复，谢谢

**Comment by zhanglaplace** [comment]
@sophiazy 我觉得这种问题，你对多样本类别采样下就可以了。

**Comment by sophiazy** [comment]
@zhanglaplace 主要因为样本最多的那一类是背景类，很复杂，采样的话对最终测试结果就会有很大影响。所以才考虑能不能用Weighted_Softmax_Loss，因为这个Weighted_Softmax_Loss适用于二分类，不知道是否适用 我这种情况
